apiVersion: sonataflow.org/v1alpha08
kind: SonataFlow
metadata:
  name: eloy
  annotations:
    sonataflow.org/description: Eloy example on k8s!
    sonataflow.org/version: 0.0.1
    sonataflow.org/profile: dev
spec:
  resources:
    configMaps:
      - configMap:
          name: service-files
        workflowPath: specs
  flow:
    functions:
    - name: book
      operation: "specs/openapi.json#get_book_book_get"
      type: rest
    start: openapiCall
    states:
    - name: openapiCall
      type: "operation"
      end: true
      actions:
      - name: "bookAction"
        functionRef:
          refName: book
          arguments:
            age: 10
            author: "${.userData}"


