---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: strimzi/kafka:0.20.1-kafka-2.6.0
        command:
        - "sh"
        - "-c"
        - "bin/zookeeper-server-start.sh config/zookeeper.properties"
        ports:
        - containerPort: 2181
        env:
        - name: LOG_DIR
          value: "/tmp/logs"

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
